# Generated by Django 3.2.9 on 2021-12-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('reg_number', models.CharField(max_length=50)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
